// Fonts
import { Bai_Jamjuree } from "next/font/google";

// Components
import { Toaster } from "sonner";

// Utils
import "./globals.css";

const bai_jamjuree = Bai_Jamjuree({
  variable: "--font-bai-jamjuree",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "IFINOS",
  description: "Generated by create next app", // talvez colocar alguma descrição no futuro?
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={bai_jamjuree.variable}>
      <body suppressHydrationWarning>
        {children}

        {/* componente para alertar o usuário com mensagens de "erro" e de "sucesso" */}
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: "#1C1C20",
              border: "0.5px solid #2A2A2E",
              color: "#E8E8E8",
            },
            classNames: {
              success: "toast_success",
              error: "toast_error",
            },
          }}
        />
      </body>
    </html>
  );
}
