// Fonts
import { Bai_Jamjuree } from "next/font/google";

// Components
import { Toaster } from "sonner";
import VLibrasWrapper from "./components/VLibrasWrapper/VLibrasWrapper";

// Utils
import "@/_lib/fontawesome";
import "./globals.css";

// Providers
import { UserProvider } from "@/context/userContext";
import ThemeProvider from "./providers/ThemeProvider";

const bai_jamjuree = Bai_Jamjuree({
  variable: "--font-bai-jamjuree",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title:
    "ifinos –  Grupo de pesquisa em Computação Física e Sistemas Embarcados",
  description: "Generated by create next app", // talvez colocar alguma descrição no futuro?
  verification: {
    google: "R8VsEz6wY6Gk2cdb5ttUjGUxxysbhso06rgxakVZuFw",
  },
  icons: {
    icon: [
      {
        url: "./favicon.webp",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={bai_jamjuree.variable}>
      <body suppressHydrationWarning>
        <ThemeProvider>
          <UserProvider>{children}</UserProvider>

          {/* componente para alertar o usuário com mensagens de "erro" e de "sucesso" */}
          <Toaster
            position="top-center"
            toastOptions={{
              style: {
                background: "#1C1C20",
                border: "0.5px solid #2A2A2E",
                color: "#E8E8E8",
              },
              classNames: {
                success: "toast_success",
                error: "toast_error",
              },
            }}
          />
          <VLibrasWrapper />
        </ThemeProvider>
      </body>
    </html>
  );
}
